LICENSE, README.md, testserver/binaries.go, testserver/testserver.go, testserver/testserver_test.go
After discussion, moving to this repo.
I've also cleaned up node.go a log and collapsed everything into
a single struct (TestServer).
Among other things:
* dump logs on unexpected failures (non-zero exits before Stop())
* cleanup temp dir
Still todo:
* download binary automatically
* use unix socket when (and if) supported by the server
=> cockroach-go/testserver: testserver using real binaries

testserver/testserver.go, testserver/testserver_test.go
Remove all the stdout parsing stuff.
PGURL waits for the socket to exist and loops forever until it does.
=> Use unix socket in testserver

testserver/binaries.go, testserver/testserver.go
* use file mode to determine whether it's finished downloading: fixes #7
* loop until system table exists: fixes #6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach-go/8)
=> Improve test server

crdb/tx.go, crdb/tx_test.go
@bdarnell
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach-go/9)
=> Rename cdb to crdb.

crdb/tx.go
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach-go/13)
=> don't overwrite errors if we fail to commit; introduce AmbiguousCommitError.

crdb/tx.go
See https://github.com/cockroachdb/cockroach/pull/6797.
This handles the server-side change where `RetriableError:CR000` has been
replaced by `SerializationFailureError:40001` for retryable transaction
errors. It maintains compatibility with older instances of CR (for now).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach-go/14)
=> Handle SerializationFailureError for retryable errors

testserver/binaries.go, testserver/testserver.go
Random fixes while looking into #20 (which this does not fix).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach-go/21)
=> fix vet, error handling

testserver/testserver.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach-go/22)
=> Fix WaitForInit. Fixes #20

testserver/testserver.go
This is needed in cases where Unix sockets cannot be used, such as with
Java and the PGJDBC driver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach-go/24)
=> Expose TCP/IP URL of TestServers

testserver/binaries.go, testserver/testserver.go, testserver/testserver_test.go
Use redirects instead. Closes #26.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach-go/27)
=> testserver: Remove dependency on .LATEST file content

testserver/binaries.go
I've verified that net/http doesn't download the entire file until
the response body is consumed (i.e. the call to http.Get is fast, and
the call to io.Copy is slow).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach-go/28)
=> testserver: use content-disposition to determine filename

testserver/testserver.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach-go/33)
=> remove stray whitespace

testserver/testserver.go, testserver/testserver_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach-go/34)
=> testserver: ensure no whitespace in URLs

crdb/tx.go, testserver/testserver.go
=> Don't swallow the original error when ROLLBACK TO SAVEPOINT fails

crdb/tx.go
Counterpart to https://github.com/cockroachdb/cockroach/pull/16928
=> Update docs links in cockroach-go repo

crdb/tx_test.go, testserver/binaries.go
=> testserver: improve error handling discipline

crdb/error.go, crdb/tx.go
Teach ExecuteInTx to detect when a retryable error has been wrapped with
errors.Wrap.
Currently, returning a wrapped error from an ExecuteInTx closure will
break automatic transaction retries, as the error is no longer directly
marked as retryable. This is particularly hard to notice when code
is split across multiple functions. Consider the following:
func doSomething(ctx context.Context, tx Tx) error {
if err := doSomethingElse(ctx, tx); err != nil {
return errors.Wrap("doSomethingElse", err)
}
}
... 8< ...
ExecuteInTx(ctx, tx, func() error {
return doSomething(ctx, tx)
})
If the actions taken by doSomethingElse cause a retryable txn error
to be returned, doSomething will wrap the error. ExecuteTx thus won't see
the retryable error and the operation will fail.
Counterpart of …
=> crdb: detect wrapped HandledRetryableError

crdb/error.go, crdb/tx_test.go
The library currently supports handling errors wrapped by pkg/errors
inside the txn closure. This patch adds similar support for go1.13
"errors" package.
Fixes #52
=> support unwrapping of go1.13 errors

crdb/tx.go
Execute runs fn and retries it as needed. It is used to add retry handling to
the execution of a single statement or single batch of statements. If a
multi-statement transaction is being run, use ExecuteTx instead.
Retry handling for individual statements (implicit transactions) is usually
performed automatically on the CockroachDB SQL gateway. As such, use of this
function is generally not necessary. The exception to this rule is that
automatic retries for individual statements are disabled once CockroachDB
begins streaming results for the statements back to the client. By default,
result streaming does not begin until the size of the result being produced
for the client, including protocol overhead, exceeds 16KiB. As long as the
results of a single statement or batch of statements are …
=> Create Execute library function

crdb/crdbsqlx/sqlx.go, crdb/crdbsqlx/sqlx_test.go
Resolves: https://github.com/cockroachdb/cockroach-go/issues/72
=> [crdb/sqlx] add sqlx adapter for crdb tx

testserver/testserver.go, testserver/testserver_test.go
The server would previously run in insecure mode. This change makes the test
environment more in line with what a production environment would be like.
This change is transparent to the client as the PGURL used is returned through
a TestServer level method, which now includes secure connection options.
=> testserver: run cockroach server in secure mode

testserver/testserver.go
The testserver package was recently changed to always use
start-single-node. However, v19.1 does not have this subcommand. To work
around this, we just try using start if start-single-node hits an error.
=> Fix start-single-node error with v19.1

testserver/testserver_test.go
See https://github.com/cockroachdb/cockroach-go/issues/87
=> Skip TestRunServer/SecureTenant

testserver/tenant.go, testserver/testserver.go, testserver/testserver_test.go
More than half of the ORMs in Examples-ORMs don't handle secure
connections well out of the box, and some outright don't support
client certs. We want to be able to at least get password auth
working over secure connections, so add an option to set that
up.
=> testserver: add option to set root password

crdb/common.go, crdb/error.go
In the future, this can be made configurable.
=> Add max retry count to retry logic

testserver/README.md
=> Add README for testserver

testserver/tenant.go
This PR adds tenant scoping to the client certs
created for accessing tenant servers. Tenant
scopes were added as a way to restrict the ability
of client certs to validate with a specific set of
tenants in v22.2. Without tenant scoping, the client
certs created for tenant servers will not be able to
connect to non system tenant servers. This PR fixes
this problem by updating the client cert generation
command to specify the tenant scope argument while
creating client certs for tenant servers.
=> Add tenant-scope arg for client certs

testserver/testserver.go, testserver/testserver_test.go, testserver/testservernode.go
Also minor changes to tests and unskipping `TestUpgradeNode`
=> Fix WaitInitForNode function

testserver/testserver.go
Using db.Ping() isn't good here, since that can succeed before the database can accept SQL commands.
=> Improve WaitForInit to be more reliable
