cockroachdb/cockroach-go

testserver/testserver.go
This prevents tests from getting the same time for the first 250ms of
operation, which is pretty confusing. Since this TestServer is a single
node, there's no point in the max offset being set to the default value.
=> Use 1ns for clock max offset

testserver/testserver.go
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach-go/11)
=> Allow database to be specified when creating testserver

crdb/tx.go, crdb/tx_test.go
... instead of our forked one. This will help people who are trying to
link in both crdb and lib/pq.
The test fix was necessary because our forked libpq has a different way
of consuming results, making exhausting the `rows` cursor somehow not
necessary.
Fixes #17
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach-go/18)
=> Move the client lib to use the standard lib/pq

testserver/testserver.go
Use the new `--listening-url-file` flag to specify a file in which the SQL URL will be written. This flag was added in cockroachdb/cockroach#15468 for exactly this purpose, and makes this testserver resilient to changes in what log output is printed where. Closes #29.
/cc @knz this solves the problem rather neatly :). Really we should never have been parsing stdout.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach-go/30)
=> testserver: use listening URL file to get SQL URL

testserver/binaries.go
Some versions of Ubuntu use eglibc ("embedded glibc") instead of glibc,
so they don't match the glibc regex.  Attempting to run the musl
binaries on these systems hangs forever. (We should probably look into
this separately; the musl binaries should work on these systems.) For
now, though, work around the issue by grepping for the less-common
"musl" rather than "glibc."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach-go/31)
=> testserver: use glibc binary on systems with eglibc

crdb/tx.go, crdb/tx_test.go
Add support for executing cockroach transactions using [GORM](https://github.com/jinzhu/gorm).
Refactor retry logic into internal function which uses an internal 
`transaction` interface.
=> Add ExecuteInTx

crdb/tx.go, crdb/tx_test.go
Clients may want to use sql package context
functionality, for example, to trace all sql
queries.
=> Add support for context

crdb/error.go, crdb/tx.go
If an error occurs attempting to rollback and that error isn't a libpq
error, then the error is currently overwritten by a string. This causes
it to lose its structure and any context it had. Instead, wrapping the
error allows callers to be able to deconstruct the error.
=> Wrap non-pq error on rollback

crdb/README.md, crdb/tx.go
This change adds code to recognize `pgx` errors as well. Note that
unlike `lib/pq`, merely importing `pgx` doesn't register a `sql`
driver (that's done by `pgx/stdlib`).
Fixes #48.
=> support pgx errors

.travis.yml, crdb/README.md, crdb/tx.go
A new version of pgx was release which no longer has a pgx.Error.
Instead, there's a new pgconn library with the errors. This commit
switches cockroach-go to work with this new library and drops support
for old pgx versions.
Fixes #54
Touches jackc/pgconn#15
=> switch to pgx v4

crdb/common.go, crdb/crdbgorm/gorm.go, crdb/crdbgorm/gorm_test.go, crdb/crdbpgx/pgx.go, crdb/crdbpgx/pgx_test.go, crdb/testing_util.go, crdb/tx.go
Before this patch, the library only had support for Go's sql package.
This patch adds subpackages for pgx and gorm, providing suitable
ExecuteTx() functions. We had a function called ExecuteInTx which was
intended to be used with transactions initiated by other frameworks.
However the function's abstraction of a Txn did not match any framework,
and the API was generally dangerous because it simply assumed that the
respective txn had not previously been used to run statements.
In contrast, the new ExecuteTx() functions work with the respective
frameworks and controls the creation of the transaction.
This patch also makes the crdb package not import a pgx package any
more.
Fixes #60
=> add support for pgx and gorm 

crdb/README.md, crdb/crdbpgx/README.md
It used to be until recently that the crdb package only supported pgx
v4. Now crdb supports v3 too, but the new crdbpgx package only supports
v4 for other reasons.
=> update readme note about pgx v4 not being supported

crdb/error.go, crdb/tx.go
There can be a mix of cause/unwrap in the error chain.
=> Fix error handling

testserver/tenant.go, testserver/testserver.go, testserver/testserver_test.go
This commit adds the NewTenantServer method to TestServer to create a new SQL
tenant pointed at that TestServer.
The first commit is #75. Once that is in, I'll rebase this.
=> testserver: add ability to start SQL tenants

crdb/crdbgorm/gorm_test.go, crdb/crdbpgx/pgx_test.go, testserver/testserver.go, testserver/testserver_test.go
Implement `StartTestServer` function that allows user to get fully started and ready to use `TestServer`. 
Here is the use case: I want a test server up and running with a single function call, the same way as it's done via function `NewDBForTest` that returns `sql.DB`. I can't use the existing function, because I connect to the database via different client e.g. `pgx`  and `TestServer` has .`PGURL()` that I can utilise.
=> Add function to fully create and start a test server

testserver/testserver.go
`cockroach start` without `--join` is deprecated behavior, and something
we're looking to get rid of in cockroachdb/cockroach#51245.
=> testserver: no longer rely on auto-init

testserver/testserver.go, testserver/version/version.go
The previous retry logic was broken due to how the package handles
errors.
Now, we check the version up front, and use `start` if necessary.
The version package is copied from the cockroachdb repo.
=> Use `start` if version is <= 19.1

testserver/testserver.go
This adds the ability to specify a custom cockroach binary via `COCKROACH_BINARY` env variable. 
Existing `--cockroach-binary` flag has more priority than the new env variable. 
See: https://github.com/cockroachdb/cockroach-go/issues/68
=> Custom cockroach binary via env variable

go.mod, testserver/tenant.go, testserver/testserver.go, testserver/testserver_test.go
- testserver: add missing tenant client certificate
- testserver: allow spinning up SQL proxy
=> testserver: fix certs and add proxy option for tenants

testserver/testserver.go
This PR aims to update the docs in regards to how the test server is used. The is an open issue that reports the details on https://github.com/cockroachdb/cockroach-go/issues/98
=> Remove call to Start() from the testserver docs

testserver/testserver.go
NewTestServer performs the check so it is redundant.
=> Remove PGURL nil check from testserver docs

go.mod, go.sum, testserver/binaries.go, testserver/testserver.go, testserver/testserver_test.go
Resolve #102
This commit is to add a flock to the local file when downloading CRDB binary.
If one process finds the localfile for CRDB binary already exists, but in unfinished 
mode and can be flocked, it means  the previous download process was killed 
before it finished. In this case, this process removes the existing local file 
and redownload CRDB binary.
Tests are added in `TestFlockOnDownloadedCRDB()` at `testserver_test.go`. 
Note that test does not fully simulate the `downloading gets killed halfway` scenario.
A recording with two downloading processes in CLI is [here](https://www.dropbox.com/s/awxvc70wfg4h0yc/testserver-redownloading.mp4?dl=0)
=> Redownload CRDB if previous download got killed in the middle

testserver/binaries.go, testserver/tenant.go, testserver/testserver.go
Implemented a `WrapError` to wrap errors from `NewTestServer`
and `NewTenantServer`. 
(Reference: `Wrapping errors with %w` in [Working with Errors in Go 1.13](https://go.dev/blog/go1.13-errors))
Also improved logging for better error trace by adding
"cockroach-go testserver:" or `cockroach-go tenantserver:`
at the beginning of log messages.
=> testserver: improve logging for better error trace

README.md, crdb/tx.go
Add a link to the pkg.go.dev documentation in the README. Also, fix the
formatting on a couple comments. The indentation of 'library' caused
godoc/pkg.go.dev to present the line as a code block.
=> README,crdb: update documentation

testserver/binaries.go, testserver/testserver.go, testserver/testserver_test.go
resolves #83
This commit sets the default mode for database downloads
to "Download the latest stable version of CRDB".
We get the latest stable version through
https://register.cockroachdb.com/api/updates, and
save it to a local file with `cockroach-majorv-minorv-patch`
naming pattern in the `tmp` directory. The downloading is
OS-specific.
**Problem unsolved**: the tenant tests with proxy always fail
with stable CRDB, but pass with latest non-stable CRDB.
=> support downloading the latest stable version of CRDB

testserver/tenant.go, testserver/testserver.go
This is needed in order to work with v22.1 (unreleased).
This also includes a small change to keep the version number as a field
on testserver.
=> Don't use placeholder for username

testserver/testserver.go
This key format is needed by Java clients.
=> testserver: generate PKCS8 key for certs

testserver/tenant.go
refs https://github.com/cockroachdb/cockroach/issues/71387
Since https://github.com/cockroachdb/cockroach/pull/71248 the server
address must be passed in as a positional argument.
Technically, the version check makes cockroach-go tenant servers not
work for commits between a0c04c620ddb67cf44265eaef61bcd38c13e4fe7 and
d7569dae28d405437f5af670346d45c2d6deb42a, but I think this is an
acceptable breakage since those are unreleased commits.
=> testserver: fix tenant-client cert arguments

crdb/common.go, go.mod
Fixes #76 
~I tried to do the minimum amount of changes to fix the issue.~
UPDATE: did a very small amount of clean up to help me understand a bit better.
There are currently no tests around this. I explored the current tests, and after a while (lots of abstraction), I was able to understand them for the most part. However, it seems that currently (and please correct me if I'm wrong) there are no existing tests actually testing the existing `defer` statement? I would have expected at least some testing of a "non-retryable" error resulting in a rollback, but either there are not any or I couldn't find them.
If someone could advise me on what tests for rollback (whether or not via `panic` or "non-retryable" error, probably should add tests for both) should look like, I'd much appreciate it …
=> rollback on panic

crdb/error.go, crdb/error_test.go
Previously, it would just show the original cause of the retries, not
the message that says it is giving up on retrying.
=> Make max retry error show correct message

crdb/error.go, crdb/tx.go
Use proper error unstacking with Go's std libraries. The current code will only check for the first level of nesting whereas Go's std libraries are able to unpack several layers of wrapping.
=> fix: user errors.As for error type assertion

crdb/common.go, crdb/tx.go, crdb/tx_test.go
Make it possible to configure maximum retry count when executing transactions.
=> Make it possible to configure maximum retry count

testserver/testserver.go
When a test server is used as a convenient in-process CRDB server for
reproducing something or showing off a feature, it's nice to be able to
view the console as well.
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
=> testserver: expose an option to serve the console

crdb/tx.go, crdb/tx_test.go, testserver/tenant.go, testserver/testserver.go
This PR adds `BaseDir() string` which exposes CRDB's root directory which helps us to, for example, load back ups when starting the database.
Please excuse the formatting noise, it is caused by `go fmt -w -s .`
=> feat: expose testserver BaseDir

testserver/testserver.go
Previously, invocations of TestServer would results in various _dump
directories being created by the cockroachdb process. While these
directories were empty, it was bothersome to see them created and
show up in file exporers. This commit sets cmd.Dir to a temporary
directory to avoid polluting the project directory of consumers.
=> set cmd.Dir to stop directory pollution

testserver/testserver.go, testserver/testserver_test.go
CockroachBinaryPath is a TestServer option that can be passed to NewTestServer
to specify the path of the cockroach binary. This can be used to avoid
downloading cockroach if running tests in an environment with no internet
connection, for instance.
=> Define CockroachBinaryPath option for testserver.

crdb/crdbgorm/gorm.go, crdb/crdbgorm/gorm_test.go
In ExecuteTx, a transaction (tx) is begun but the error check only looks for errors in the original db object. If the transaction fails to start, the error is not caught immediately.
=> Check tx error rather than db error in ExecuteTx

testserver/testserver.go, testserver/testserver_test.go
The teamcity build for cockroachdb repo uses
a relative path for setting a custom cockroach
binary. This change resolves the relative path
to an absolute path. This way updating the command's
base directory does not impact the cockroach binary
look up while running example-orm tests.
=> Update crdb binary path to absolute

testserver/testserver.go, testserver/testserver_test.go
Previously it was using hardcoded ports, to allow parallel runs we want to be able to specify nodes.
It is on the user to make sure when a node is specified, that port cannot be stolen away during a node restart.
=> Require specifying ports when using multiple nodes

go.mod, testserver/testserver.go, testserver/testserver_test.go
This PR adds `ExternalIODirOpt` in order to let users specify the `--external-io-dir` startup option. This will let users test how their application functions in backup and restore operations without having to use an on-disk testserver.
I also noticed that while `require` was used in `testserver_test.go`, it was not imported in `go.mod`, so I added it in.
=> Add External IO Dir TestServerOpt

testserver/binaries.go, testserver/testserver.go, testserver/testserver_test.go
This PR allows users to specify a custom cockroach binary version as opposed to only allowing them to download the latest stable or unstable version.
=> Allow for custom cockroach binary versions

testserver/testserver.go, testserver/testserver_test.go, testserver/testservernode.go
- Fix race condition in pollListeningURLFile.
- Add Opts for init node timeout and poll listening url.
- InitTimeoutOpt, PollListenURLTimeoutOpt
- Parallelize restart test
=> Make testserver multi-node more robust.

testserver/testserver.go, testserver/testserver_test.go
Previously, the port option could only be overridden if you were running multiple cockroach nodes. This commit changes the behavior such that you can override from port `0` to any arbitrary port in the single node configuration.
=> Allow single node clusters to override port

.github/workflows/ci.yaml, .gitignore, testserver/binaries.go
After we moved the edge CDN to GCS-backed Google CDN, the latest binaries became actual binaries, without redirects, as it was before.
This PR removes the redirect resolution logic.
I also pinned clrfmt to the version that doesn't use generics and added go-1.19 to the test matrix.
=> Do not use redirects for latest binaries

go.mod, testserver/version/version.go
=> remove github.com/pkg/errors dependency

.github/workflows/ci.yaml, testserver/binaries.go, testserver/tenant.go, testserver/testserver.go, testserver/testservernode.go
This also changes the per-node store directories so they are all inside
the base directory.
=> Use separate stdout/stderr for each node

testserver/testserver.go, testserver/testserver_test.go
Previously, the testserver could only listen on localhost. This meant that there was no way to spin up an instance of the testserver on one machine and access it from another. This commit adds support for custom hosts so that the testserver can be accessed from outside hosts if needed.
For my use case, I need this so that I can have a docker-compose file with two services: one for the testserver and one for my go tests. For the networking to work out, I need to be able to listen on `0.0.0.0` not `localhost`.
=> Support custom host on listen address

testserver/testserver.go
This will be useful for cockroachdb CI, which has logic that can preserve temporary files in TMPDIR in the CI artifacts.
It's safe to remove the logic to use "/tmp" since that was initially added in a2ed1c60, but it's no longer needed since the testserver no longer creates UNIX sockets.
=> testserver: respect the TMPDIR environment variable

testserver/tenant.go, testserver/testserver.go, testserver/testserver_test.go, testserver/testservernode.go
This required the join and init args to be computed on the fly, since we can no longer infer them until after a node has started.
informs https://github.com/cockroachdb/cockroach/issues/98549
informs https://github.com/cockroachdb/cockroach/issues/98612
informs https://github.com/cockroachdb/cockroach/issues/98594
=> Allow non-hardcoded ports for multinode cluster

testserver/testserver.go, testserver/testserver_test.go
This commit adds the `testserver.LocalityFlagsOpt` option. The flag makes it possible to test multi-region primitives with the test server.
=> testserver: add support for the --locality flag

testserver/testserver.go, testserver/testserver_test.go
This new parameter allows callers to specify a root directory where logs for cockroach processes created by testserver will be located.
Previously, when calling `testserver.Stop()`, *all* resources would be deleted, including cockroach logs. By allowing the caller to specify a custom directory, we allow the possibility for the logs to outlive the cockroach processes, which is especially useful when debugging test failures.
=> testserver: introduce CockroachLogsDirOpt

testserver/testserver.go
This commit adds the `--logtostderr` command line flag when starting a cluster with multiple nodes, making the behavior consistent with single-node clusters. In addition, this makes the change introduced in 68fede3 more useful, as the stderr will include the actual cockroach logs.
=> testserver: pass `logtostderr` when starting multiple nodes

testserver/binaries.go, testserver/testserver_test.go
Previously, the testserver would always make a get request to download
the cockroach binary. This commit short circuits the download logic to
avoid making the initial request if the file already exists.
=> testserver: short circuit downloading before making a request

testserver/binaries.go, testserver/testserver.go, testserver/testserver_test.go
fixes https://github.com/cockroachdb/cockroach-go/issues/174
The code was previously looking at the /api/updates endpoint on the register.cockroachdb.com server. However, that endpoint returns Cloud Only releases, which cannot be downloaded from binaries.cockroachdb.com.
Now we use the releases list maintained by the docs team, which lets us filter out undesired releases.
=> Switch to docs page to determine latest stable version

testserver/testserver.go
informs https://github.com/cockroachdb/cockroach/issues/119897
=> Add option to configure cache size

testserver/testserver.go, testserver/testservernode.go
The asynchronous code that polls for the URL file leads to very opaque failures. This change reworks this code to waiting synchronously, so that we know the server is started before we return. In cases of failure, we now get more useful errors.
=> testserver: fix URL file polling code
